version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - VITE_API_BASE=http://localhost:5269/api
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  api:
    build:
      context: ./B2BMusicStreamingPlatformwebapi
      dockerfile: Dockerfile
    ports:
      - "5269:5269"
    depends_on:
      - db
    environment:
      - PostgreSQLDbConnStr=Host=db;Port=5432;Database=b2b_music;Username=postgres;Password=superuser

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=superuser
      - POSTGRES_DB=b2b_music
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
